FROM quay.io/minio/minio

RUN mkdir /storage

VOLUME /storage

ENV MINIO_ROOT_USER=storage_admin
ENV MINIO_ROOT_PASSWORD=storage_password
ENV MINIO_VOLUMES="/storage"
EXPOSE 9000
EXPOSE 9090

CMD ["minio", "server", "/storage", "--console-address", ":9090"]
